canary:
  threads: 10
  endpoints: [{
    name: 'something',
    url: 'somewhere',
    pollFrequencySec: 2,
    secret: 'thisIsSecret'
  },
  {
    name: 'somethingElse',
    url: 'somewhereElse',
    pollFrequencySec: 5
}]

canaryMonitor:
  httpClient:
    maxConnections: 20
    connectTimeoutInMillis: 5000

spring:
  devtools:
    livereload:
      enabled: true
      port: 35729
